{"name": "Проверка увеличения счетчика В работе после создания заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_feed_page.TestFeedOrdersPage object at 0x107c477a0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"9a9f0cd7-23f2-4ac8-880f-8c35aa14bc64\")>\nlogin_user_and_create_order = ('elise_18@example.net', 'oiiovfzdzzpu', '146283')\n\n    @allure.title('Проверка увеличения счетчика В работе после создания заказа')\n    def test_check_rise_counter_at_work_after_made_order(self, driver, login_user_and_create_order):\n        login_page = LoginPage(driver)\n        login_page.open_login_page()\n        number = login_page.user_login_with_order(login_user_and_create_order)\n        feed_page = FeedPage(driver)\n        feed_page.open_feed_page()\n>       number_in_at_work = feed_page.check_number_order_in_at_work()\n\ntests/test_feed_page.py:69: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/feed_page.py:32: in check_number_order_in_at_work\n    self.wait_for_element(FeedPageLocators.ORDER_NUMBER_LIST, 'visibility')\npages/base_page.py:26: in wait_for_element\n    WebDriverWait(self.driver, 20).until(condition(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"9a9f0cd7-23f2-4ac8-880f-8c35aa14bc64\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x1112ca660>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Открываем страницу логина", "status": "passed", "start": 1730240959489, "stop": 1730240965805}, {"name": "Авторизация пользователя с созданием заказа", "status": "passed", "parameters": [{"name": "login_user_and_create_order", "value": "('elise_18@example.net', 'oiiovfzdzzpu', '146283')"}], "start": 1730240965805, "stop": 1730240966078}, {"name": "Открываем страницу Ленты заказов", "status": "passed", "start": 1730240966078, "stop": 1730240969823}, {"name": "Проверяем появление номер заказа в разделе В работе на Ленте заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/Users/lnlydrvr/Documents/Diplom_3/pages/feed_page.py\", line 32, in check_number_order_in_at_work\n    self.wait_for_element(FeedPageLocators.ORDER_NUMBER_LIST, 'visibility')\n    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/lnlydrvr/Documents/Diplom_3/pages/base_page.py\", line 26, in wait_for_element\n    WebDriverWait(self.driver, 20).until(condition(locator))\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1730240969823, "stop": 1730240990255}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1730240959489, "stop": 1730240990262, "uuid": "6bb4995d-75b1-4bab-a9df-3b97deea7fb0", "historyId": "6fd343b5b9eca471e26859b5c10dd312", "testCaseId": "27b2f9844738225b9ffb78d54432586e", "fullName": "tests.test_feed_page.TestFeedOrdersPage#test_check_rise_counter_at_work_after_made_order", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed_page"}, {"name": "subSuite", "value": "TestFeedOrdersPage"}, {"name": "host", "value": "MBP-Roman"}, {"name": "thread", "value": "5805-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed_page"}]}